### ISSUE TITLE
Error starting issue

### ISSUE THREAD

**Issue by JasonBenfield** [JasonBenfield/HubWebApp#209]
Gis/issues 280

System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1437
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 205
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1492
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 205
   at Octokit.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy) in /_/Octokit/SimpleJson.cs:line 584
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in /_/Octokit/SimpleJson.cs:line 596
   at Octokit.Internal.SimpleJsonSerializer.Deserialize[T](String json) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 22
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in /_/Octokit/Http/JsonHttpPipeline.cs:line 62
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 696
   at Octokit.ApiConnection.Get[T](Uri uri, IDictionary`2 parameters) in /_/Octokit/Http/ApiConnection.cs:line 72
   at XTI_GitHub.Web.WebXtiGitHubRepository._Issue(Int32 number)
   at XTI_GitHub.XtiGitHubRepository.StartIssue(XtiGitVersion version, Int32 issueNumber)
   at XTI_Admin.StartIssueCommand.Execute() in C:\XTI\src\JasonBenfield\HubWebApp\HubWebApp\Internal\XTI_Admin\StartIssueCommand.cs:line 26
   at XTI_AdminTool.HostedService.StartAsync(CancellationToken cancellationToken) in C:\XTI\src\JasonBenfield\HubWebApp\HubWebApp\Tools\XTI_AdminTool\HostedService.cs:line 32

**Comment by JasonBenfield** [comment]
System.InvalidCastException: Unable to cast object of type 'ContentLengthReadStream' to type 'System.Byte[]'.
   at XTI_GitHub.Web.WebXtiGitHubRepository._DownloadReleaseAsset(GitHubReleaseAsset asset)
   at XTI_Admin.GitHubPublishedAssets.LoadVersions(String releaseTag) in C:\XTI\src\JasonBenfield\HubWebApp\HubWebApp\Internal\XTI_Admin\GitHubPublishedAssets.cs:line 112
   at XTI_Admin.InstallProcess.Run() in C:\XTI\src\JasonBenfield\HubWebApp\HubWebApp\Internal\XTI_Admin\InstallProcess.cs:line 50
   at XTI_Admin.PublishAndInstallCommand.Execute() in C:\XTI\src\JasonBenfield\HubWebApp\HubWebApp\Internal\XTI_Admin\PublishAndInstallCommand.cs:line 20
   at XTI_AdminTool.HostedService.StartAsync(CancellationToken cancellationToken) in C:\XTI\src\JasonBenfield\HubWebApp\HubWebApp\Tools\XTI_AdminTool\HostedService.cs:line 32
